Neutrino Mass Matrices

In [56]:

import numpy as np
import sympy as sy
import math
from numpy.random import default_rng
# import matplotlib as plt

Definimos las matrices de Gell-Mann

In [209]:
l0 = (np.sqrt(2/3))*np.array([[1,0,0],[0,1,0],[0,0,1]])
l1 = np.array([[0,1,0],[1,0,0],[0,0,0]])
l2 = np.array([[0,-1j,0],[1j,0,0],[0,0,0]])
l3 = np.array([[1,0,0],[0,-1,0],[0,0,0]])
l4 = np.array([[0,0,1],[0,0,0],[1,0,0]])
l5 = np.array([[0,0,-1j],[0,0,0],[1j,0,0]])
l6 = np.array([[0,0,0],[0,0,1],[0,1,0]])
l7 = np.array([[0,0,0],[0,0,-1j],[0,1j,0]])
l8 = (1/math.sqrt(3))*np.array([[1,0,0],[0,1,0],[0,0,-2]])

lam = np.array([l0,l1,l2,l3,l4,l5,l6,l7,l8])
# print('l1=', l1, 'l2=', l2, 'l3=', l3 , 'l4=',l4 ,'l5=',l5 , 'l6=', l6, 'l7=',l7 , 'l8',l8)

Definimos un producto punto entre matrices

In [242]:

matrixdot(lam[8],lam[8])

(1.0000000000000002+0j)

In [260]:
I=np.ones((3,3))
Ra=default_rng(42).random((3,3))

R=np.dot(Ra,lam[n])

def matrixdot(A,B):
    return np.trace(A@B)/2

def matrixcoeff(A):
    cr =np.zeros(shape=(9), dtype = 'complex_')
    for n in range(0,9):
        cr[n] = matrixdot(A,lam[n])
    return cr

In [261]:
# (matrixdot(lam[0], Ra)) 
(matrixcoeff(lam[8]))


array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       1.+0.j])

In [262]:

np.einsum('i,ijk',matrixcoeff(Ra),lam)


array([[0.77395605+0.j, 0.43887844+0.j, 0.85859792+0.j],
       [0.69736803+0.j, 0.09417735+0.j, 0.97562235+0.j],
       [0.7611397 +0.j, 0.78606431+0.j, 0.12811363+0.j]])

In [264]:
Ra - np.einsum('i,ijk',matrixcoeff(Ra),lam)

array([[ 0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j],
       [ 0.00000000e+00+0.j, -2.77555756e-17+0.j,  0.00000000e+00+0.j],
       [ 0.00000000e+00+0.j,  0.00000000e+00+0.j,  1.11022302e-16+0.j]])

In [247]:

matrixdot(lam[8],lam[8])
   

(1.0000000000000002+0j)

In [257]:
matrixcoeff(lam[8])

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j])

In [255]:

matrixdot(lam[8],lam[8])

(1.0000000000000002+0j)

In [259]:
for n in range(0,9):
        print(n)

0
1
2
3
4
5
6
7
8
